### PR TITLE
feat: Add a toggle for alternative sources

### PR DESCRIPTION
**Pull request by TheAabedKhan**
Some Screenshots

|Before|After (Disabled)|After (Enabled)|
|-----|----|---|
|image|image|image|

# Test

- [x] When using the alternative source, the patches card in home updates accordingly and the patches do too
- [x] Casing has no effect for alternative sources
- [x] Resetting works
- [x] Migration works

### CODE REVIEW

**Review by Aunali321 — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
@Aunali321 the checkboxes above are unticked. Have you tested them?

**Comment by Aunali321** [comment]
@oSumAtrIX @TheAabedKhan  at the time of review, you asked me to do code review after i raised an issue with UI. Today i go ahead with full test and found only single issue. After turning on alternative sources toggle, changing sources and turning it off, it shows no applications found. It should show default patches.

**Comment by TheAabedKhan** [comment]
> After turning on alternative sources toggle, changing sources and turning it off, it shows no applications found. It should show default patches.

Have you tried restarting the app? Can you attach a screen recording of the test?

**Comment by Aunali321** [comment]
https://github.com/ReVanced/revanced-manager/assets/48486084/b961806a-c1fd-4d95-af0d-4ae0dd0bac75

**Comment by Aunali321** [comment]
Fixed.

**Pull request merged**
