### PR TITLE
feat: update icons for the new logo

### LINKED ISSUE #918: fix: update branding
## About

ReVanced brandings have updated

## Issue

The current branding is outdated

## Solution

Update the current branding to the new one according to the following:
https://github.com/revanced/revanced-branding

### PR DESCRIPTION
**Pull request by YarostheLaunchpadder**
fixed #918

The icon is adaptive according to the docs: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

### CODE REVIEW

**Comment by Ushie** [comment]
Could you use the no-ring variant? There are more shapes than circle to count for

**Comment by YarostheLaunchpadder** [comment]
Sure. Will do so. But only for the launcher icon? Or for the notification icon as well? @Ushie

**Review by EvadeMaster — APPROVED** [review]
:arrow_up_small: Look good to me, 

would be great if we switch back to the no-ring variant like Ushie suggest, that way it should make it distinguish from YouTube ReVanced which uses ring variant.

**Comment by YarostheLaunchpadder** [comment]
Perfect. I will make the new SVG variant without the ring, so it will look on all devices. 
But should I leave the legacy icon (.png) with the ring as it can't be another shape?

**Review by Aunali321 — APPROVED** [review]

**Comment by YarostheLaunchpadder** [comment]
@Ushie Yes, monochrome should be updated and work.

**Pull request merged**
