### PR TITLE
feat: add haptic feedback

### PR DESCRIPTION
**Pull request by BenjaminHalko**
Adds haptic feedback to switches, radios, buttons, and checkboxes.

### CODE REVIEW

**Comment by validcube** [comment]
Some people might find this annoying, would recommend an toggle for haptic.

**Comment by Ushie** [comment]
Haptics are a system level toggle, if they find it annoying they'd have already disabled it

**Comment by validcube** [comment]
> @Ushie Haptics are a system level toggle, if they find it annoying they'd have already disabled it

Fair

**Comment by Ushie** [comment]
Hey, @validcube and I tested this PR and we can't get haptics to show up

**Comment by validcube** [comment]
> Hey, @validcube and I tested this PR and we can't get haptics to show up, does it work on your side?

Noper:tm:

**Review by validcube — DISMISSED** [review]
🚧 Merging is blocked: we couldn't get the haptic feature to work

Please dismiss this review and scream at us in [team chat](https://canary.discord.com/channels/952946952348270622/952987428786941952) if you think this is the result of our skrill issue.

**Comment by Ushie** [comment]
Turns out that the PR Build workflow has a problem, and does not include the changes in the PR

I'll retest this PR in a bit

**Comment by Ushie** [comment]
Hey, @validcube or @TheAabedKhan do you think it's possible to test this?

I don't have the time to build and test this

**Comment by validcube** [comment]
> Hey, @validcube or @TheAabedKhan do you think it's possible to test this?
> 
> I don't have the time to build and test this

I remember building & testing this, and the haptic doesn't work.

Could be an problem on my end but I'll retest it just to be sure.

**Review by validcube — DISMISSED** [review]
I recently tested this with `release` and `debug` variants, but for some reason I couldn't get this to work, can you check it again?

**Comment by BenjaminHalko** [comment]
@validcube It works for me...

**Comment by validcube** [comment]
> @validcube It works for me...

:+1: Alright, I'll dismiss the reviewer for this PR for now as I cannot verify this, could be issue on my end.

**Review by Aunali321 — APPROVED** [review]
Looks good to me

**Comment by madnotfromthemadmagazineconclusion** [comment]
I've been dealing with the haptic feedback for two weeks now. It's driving me crazy not being able to turn it off on the video bar in YT. Haptic feedback was always there. Why not in 1.24. I don't want to use YT like this. Is there a solution? I can't turn Quic protocol on and off either. There aren't that many great patches left.

**Pull request merged**
