### PR TITLE
feat: add option to import/export keystore

### PR DESCRIPTION
**Pull request by andrisas**
add option to import/export keystore used to sign apks

### CODE REVIEW

**Comment by Ushie** [comment]
@oSumAtrIX @Aunali321 how should ReVanced Manager ask for the imported keystore's password? should it just be an extra textbox in the popup or should it be a followup popup?

**Comment by andrisas** [comment]
I do not think a password is necessary unless you use a keystore that is not generated by revanced

**Comment by Aunali321** [comment]
> I do not think a password is necessary unless you use a keystore that is not generated by revanced

What if i want to use keystore from PC which i generated using ReVanced Cli with different password?

**Comment by andrisas** [comment]
added option to change the keystore password

**Comment by oSumAtrIX** [comment]
@revanced/manager Should be ready for a review.

**Review by Aunali321 — APPROVED** [review]
Works as expected, Thanks!

**Pull request merged**
