### PR TITLE
refactor: remove unimplemented features

### PR DESCRIPTION
**Pull request by validcube**
### ✨ remove not implemented features

image

### CODE REVIEW

**Comment by TheAabedKhan** [comment]
So, closing #1039 as not planned?

**Comment by validcube** [comment]
> So, closing #1039 as not planned?

Yup :up:

**Comment by Ushie** [comment]
Should the update/patch button in app info be removed along with this?

**Comment by validcube** [comment]
> Should the update/patch button in app info be removed along with this?

Done!:tm:

**Review by Ushie — APPROVED** [review]

**Comment by Ushie** [comment]
Could you delete all the language JSON files aside from English?

**Pull request merged**
