### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by AmanSikarwar**
Updated dependencies to latest version

- re-implemented cache interceptor using [dio_cache_interceptor](https://pub.dev/packages/dio_cache_interceptor) because [dio_cache_manager_lts](https://pub.dev/packages/dio_http_cache_lts) has not got any update for a while and is incompatible with latest [dio](https://pub.dev/packages/dio)
- migrated to latest [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) that include some breaking changes
- replaced native_dio_client with [native_dio_adapter](https://pub.dev/packages/native_dio_adapter)
- removed unused dependencies from pubspec.yaml
- minor code refactor

Everything is tested and working as per expectations

### CODE REVIEW

**Comment by Aunali321** [comment]
@AmanSikarwar Thank you for the contribution but
1. `re-implemented cache interceptor using [dio_cache_interceptor](https://pub.dev/packages/dio_cache_interceptor) because [dio_cache_manager_lts](https://pub.dev/packages/dio_http_cache_lts) has not got any update for a while and is incompatible with latest [dio](https://pub.dev/packages/dio)`

and

3. `Replaced native_dio_client with [native_dio_adapter](https://pub.dev/packages/native_dio_adapter)`

are already done on https://github.com/revanced/revanced-manager/pull/752/commits/c2021d508eb05bfd48d3b65d8ff440dd41311273.

Would love to merge other changes, can you comply with the changes? Thanks!

**Comment by AmanSikarwar** [comment]
@Aunali321 I have reverted

- re-implemented cache interceptor using [dio_cache_interceptor](https://pub.dev/packages/dio_cache_interceptor)

Now it should comply with your changes, Thanks!

**Comment by oSumAtrIX** [comment]
@revanced/manager Should be ready for a review.

**Comment by Aunali321** [comment]
@AmanSikarwar Can you fix this conflicts so i can merge?

**Comment by AmanSikarwar** [comment]
@Aunali321 I have fixed the conflicts, now it is ready to merge. Thanks!

**Comment by Aunali321** [comment]
Thanks for the contribution!

**Comment by AmanSikarwar** [comment]
Thanks for merging my pull request

**Pull request merged**
