### PR TITLE
feat(updater): download successful dialog

### PR DESCRIPTION
**Pull request by TheAabedKhan**
When a user knowingly or unknowingly cancels or closes the installer window, there must be a dialog box which allows the user to launch the installer window again.
revanced_ui

### CODE REVIEW

**Comment by ILoveOpenSourceApplications** [comment]
If this UI/UX change is the same as the screenshot, then I would like to suggest some changes. "Update downloaded!" text being shown in place of the progress bar, could be placed in the position of "downloading update...". Once they download completes, the text could change into "Download completed"/"Update downloaded" and then the user can update by tapping the update button.

**Comment by Ushie** [comment]
After you resolve the issue raised in the comment above, this can be merged

**Comment by TheAabedKhan** [comment]
New UI after fixes

revanced_updater_new

**Comment by Ushie** [comment]
Maybe the Update button should be renamed to Install instead?

**Comment by Ushie** [comment]
I think the progress bar doesn't need to be there anymore, what about text instead? "Do you want to install this update?" or something along the lines of that

**Comment by ILoveOpenSourceApplications** [comment]
> Maybe the Update button should be renamed to Install instead?

I second this. Why press update twice, when downloading and installing.

> I think the progress bar doesn't need to be there anymore, what about text instead? "Do you want to install this update?" or something along the lines of that

Would make more sense with this as well.

**Comment by TheAabedKhan** [comment]
> "Do you want to install this update?" or something along the lines of that

The package installer will automatically open after the update is downloaded so a user can't see what's written on the dialog box. If the user mistakenly cancels the installer, then the user can see the text that says, "Continue to install the update?" which makes more sense.

**Comment by Ushie** [comment]
That text sounds good

**Comment by Ushie** [comment]
Have you been able to make time to update the text?

**Comment by TheAabedKhan** [comment]
> Have you been able to make time to update the text?

What text to what?

**Comment by Ushie** [comment]
Oh my mistake, completely missed that commit

**Pull request merged**
