### PR TITLE
build: bump version to 1.3.0

### PR DESCRIPTION
**Pull request by MrAngelos6**
You forgot to update pubspec.yaml file with the latest release.

### CODE REVIEW

**Comment by MrAngelos6** [comment]
@oSumAtrIX Do i need to put the version at 1.3.1+100300100 ? You need to push another tag right ?

**Comment by Ushie** [comment]
oh 😅 sorry!

**Comment by Ushie** [comment]
> @oSumAtrIX Do i need to put the version at 1.3.1+100300100 ? You need to push another tag right ?

Yes please do 1.3.1

**Comment by MrAngelos6** [comment]
@Ushie It's good 😄

**Comment by Ushie** [comment]
Sorry about this, could you revert that last commit to bring it back to 1.3.0? I hastily deleted the release

**Comment by MrAngelos6** [comment]
@Ushie No problem, i reverted 😁

**Pull request merged**
