### PR TITLE
feat: add haptic feedback

### PR DESCRIPTION
**Pull request by BenjaminHalko**
Adds haptic feedback to compose

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Is this ready for review?

**Review by Ushie — CHANGES_REQUESTED** [review]
I've had this review pending for a month's time, apparently I never clicked submit review..

**Review by Axelen123 — CHANGES_REQUESTED** [review]
Why are there so many unrelated formatting changes in files that don't have anything to do with haptics?

**Comment by Ushie** [comment]
> Why are there so many unrelated formatting changes in files that don't have anything to do with haptics?

Didn't notice, I installed KTLint and I guess these were files that I visited

**Review by Ushie — APPROVED** [review]

**Pull request merged**
