### PR TITLE
feat: show warning when apk min-sdk is higher than device sdk

### PR DESCRIPTION
**Pull request by shabbyplace**

### CODE REVIEW

**Comment by shabbyplace** [comment]
Only YouTube requires Android 8.0 and up. Older Android versions are still supported by YouTube Music, Twitter, and Tiktok. However, because the manager sdk is configured for Android 8.0. Users of older devices cannot use the patcher to patch the these apps.

**Comment by Aunali321** [comment]
@ponces what do you think about this?

**Comment by ponces** [comment]
Why does this have an impact of min sdk of manager itself?

**Comment by shabbyplace** [comment]
There are still Android 6 and 7 devices used by some. TikTok, for example, continues to support these versions. If the manager only supports Android 8 and up, these devices will be unable to install the manager. As a result, they are unable to patch other apps that still support their Android version.

**Comment by Ushie** [comment]
> There are still Android 6 and 7 devices used by some. TikTok, for example, continues to support these versions. If the manager only supports Android 8 and up, these devices will be unable to install the manager. As a result, they are unable to patch other apps that still support their Android version.

ReVanced Manager only works with SDK 26 and up, otherwise it'd of already had a lower min SDK

**Pull request closed without merging**
