### PR TITLE
feat(style): use native switch & chip + cleanup

### PR DESCRIPTION
**Pull request by EvadeMaster**
# 🎯 Features
c814fd6a4b6000581d72fc6e537d9876bc41474f - Use a native switch component
1a116cf7ec21c0eaf7cce09a223e27922b9099ce - Use a native chip component

# 🧹 Task Force Cleanup
### Theme
91a3120805817c296bf0b81c63c87b46142e9155 - Let flutter automatically choose Material 3 colour
c01dbb15dee54ed280d5e13320fc35dd6a64e4fa - Correct M3 theme for non-dynamic theme
e8b3b99f56e4a6e71d03cd106edca90bbd1e6e72, 3b4d448048b9a49707c5366ffa1ed183d8fe84ab, 94eb5b5fe220717ffda3ef428818f0b28e4232b7 - Cleanup
### Accessibility
cf5ec01dbcec93cb74dfa1eb29c5bdce72f4f94b - Add tooltips to the dashboard
> Useful for using Talkback reader

b1187165e9a2415fbb162076f8a89aa2e4fd7bff - Add translation string for "recommended", "all", and "none" tooltip
> Improve clarity for people using Talkback reader

### CODE REVIEW

**Comment by EvadeMaster** [comment]
# Preview

Home:
image

Settings:
image

**Comment by xafn** [comment]
i love you

**Comment by Indranil012** [comment]
that "update manager" button looks weird, it might be better if the button get hidden if no update available.

**Comment by EvadeMaster** [comment]
> that "update manager" button looks weird, it might be better if the button get hidden if no update available.

Feel free to open an [issue here](https://github.com/revanced/revanced-manager/issues/new/choose) under `Feature > Cosmetic`. 👍

**Review by Aunali321 — APPROVED** [review]

**Pull request merged**
