### PR TITLE
feat: Support install and update vanced microg

### LINKED ISSUE #545: bug: heavy load on api
### Type

Error while running the manager

### Bug description

The ReVanced Manager hits the API multiple times when not necessary. Relevant code is used in multiple places:
https://github.com/revanced/revanced-manager/blob/f1261398e927903f6c75c44f5d03fdff562bda47/lib/services/revanced_api.dart#L83-L100

### Screenshots or videos

[All of these call the API each time](https://github.com/revanced/revanced-manager/blob/0faf86c9e949f82e8fdc6e33ae561cc5cca5b42f/lib/services/manager_api.dart):
image

### Solution

Instead of hitting the API multiple times, it is only necessary to do so once and then read the fields from the parsed model.

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

### PR DESCRIPTION
**Pull request by cvphat**
- Allow user install and update Vanced microG in dashboard
- Resolve #545

### CODE REVIEW

**Comment by Ushie** [comment]
ReVanced Manager is app agnostic, it has nothing to do with Vanced MicroG and it should not manage it nor offer to download/install it

**Comment by oSumAtrIX** [comment]
@Ushie is correct, Vanced MicroG is required by the `microg-support` patch for YouTube. For that reason it is the patches task to manage or offer downloading and installing it.

**Comment by cvphat** [comment]
@Ushie The [ReVanced Tools](https://releases.revanced.app/docs#/ReVanced%20Tools)  has vanced microg. So I think it is helpful for non root user to use.
image

**Comment by oSumAtrIX** [comment]
@cyphat This is a bug and should be removed from here:

https://github.com/revanced/revanced-releases-api/blob/main/config.toml

**Comment by Ushie** [comment]
> @Ushie The [ReVanced Tools](https://releases.revanced.app/docs#/ReVanced%20Tools) has vanced microg. So I think it is helpful for non root user to use. image

We'll let the API team know that it should be removed.

**Comment by cvphat** [comment]
> ReVanced Manager is app agnostic, it has nothing to do with Vanced MicroG and it should not manage it nor offer to download/install it

So, I am going to close this PR

**Comment by Ushie** [comment]
> > ReVanced Manager is app agnostic, it has nothing to do with Vanced MicroG and it should not manage it nor offer to download/install it
> 
> So, I am going to close this PR

Yes, please open a new PR regarding #545

**Pull request closed without merging**
