### PR TITLE
docs: init

### PR DESCRIPTION
**Pull request by BenjaminHalko**
Now it is slightly clearer how to build the manager.

TODO:
- [x] Step 5 requires that #1223 be merged as currently Gradle does not check `~/.gradle/gradle.properties`

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Building steps are under /docs:

https://github.com/ReVanced/revanced-manager/blob/main/docs/4_building.md

**Comment by BenjaminHalko** [comment]
@oSumAtrIX done

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
LGTM, with the docs there is one more workflow associated to dispatch an event on pushes to /docs. Please add it to this PR.

**Comment by BenjaminHalko** [comment]
@oSumAtrIX done

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
