### PR TITLE
Russian and Ukrainian translation 

### PR DESCRIPTION
**Pull request by Dialynx**

### CODE REVIEW

**Comment by Dialynx** [comment]
Not sure if "values-ru/ua" is correct folder name tho 🙂

**Comment by Canny1913** [comment]
correct names are values-uk-rUA and values-ru-rRU

also they both already exist but idk if they are correct

https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-ru-rRU/strings.xml

https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-uk-rUA/strings.xml

**Comment by Dialynx** [comment]
> correct names are values-uk-rUA and values-ru-rRU
> 
> also they both already exist but idk if they are correct
> 
> https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-ru-rRU/strings.xml
> 
> https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-uk-rUA/strings.xml

Ok, let me check

**Comment by Dialynx** [comment]
All seems fine. Thanks for support, closing the pull req now

**Comment by Canny1913** [comment]
Keep in mind that Manager isn't complete so more strings may be added in the future.

**Comment by Dialynx** [comment]
> correct names are values-uk-rUA and values-ru-rRU
> 
> also they both already exist but idk if they are correct
> 
> https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-ru-rRU/strings.xml
> 
> https://github.com/revanced/revanced-manager/blob/1a498e629213858c16ad0b489901218e3c216d1e/app/src/main/res/values-uk-rUA/strings.xml

Also, all translation strings are deleted, isn't it?
https://github.com/revanced/revanced-manager/commit/b3a37e3251d905f7396a52324b32bfce6f600d49

**Pull request closed without merging**
