### PR TITLE
Added Support for Swahili language

### PR DESCRIPTION
**Pull request by AngelofVerdant**
Added an empty JSON file for Swahili translation since Swahili is not an option on Crowdin translate.

### CODE REVIEW

**Comment by Ushie** [comment]
I added Swahili Kenya to the list of languages in Crowdin, please do this there instead as we have uploading translations project-side disabled

**Comment by AngelofVerdant** [comment]
Sure thing. However , Swahili still isn't available on crowdin. I just checked

**Comment by Ushie** [comment]
Updated, should be there now, i figure i left the page before saving

**Comment by AngelofVerdant** [comment]
Okay cool, And how long after full translation is it merged to source?

**Comment by Ushie** [comment]
There is a cronscript that gets updated translations from Crowdin daily, but in a different branch

We don't have specific requirements for merging to main, if you want you can mention me once the translation is done and I'll merge it to the main branch

**Comment by AngelofVerdant** [comment]
Okay , thanks, will do

**Comment by AngelofVerdant** [comment]
> There is a cronscript that gets updated translations from Crowdin daily, but in a different branch
> 
> We don't have specific requirements for merging to main, if you want you can mention me once the translation is done and I'll merge the translations branch to the main branch

Hello, the Swahili translation is done. Requesting you review and merge to main 💪

**Pull request closed without merging**
