### PR TITLE
docs: use correct directory path

### PR DESCRIPTION
**Pull request by n30mrx**
the ~ symbol leads to the home directory, I changed it to . so  it can point to the current directory

### CODE REVIEW

**Comment by n30mrx** [comment]
oh lol that PR merged😂
this is the coolest achievement I made

**Comment by validcube** [comment]
> @n30mrx oh lol that PR merged😂 this is the coolest achievement I made

❤️ Thank you for your contributions! ;)

**Comment by oSumAtrIX** [comment]
Why should the Gradle properties file be edited for the local project? @validcube

**Comment by Ushie** [comment]
haven't acknowledged the move to mavenCentral yet, should open an issue

**Comment by oSumAtrIX** [comment]
The properties file is indeed not needed anymore.

**Comment by validcube** [comment]
> @oSumAtrIX Why should the Gradle properties file be edited for the local project? @validcube

:husk: I was not informed

**Pull request merged**
