### PR TITLE
feat: improved icon & splash screen

### LINKED ISSUE #504: bug: Use different icons for Youtube Revanced and Revanced Manager
image

We should use a different icon for the Manager to distingush Youtube Revanced and RM.

### PR DESCRIPTION
**Pull request by kazimmt**
Closes #504.

### CODE REVIEW

**Comment by kazimmt** [comment]
@oSumAtrIX I test it manually (Decompiling the app, add new file, compile the app on mobile)
Works for me tho,

Test before merge is recommended.

**Comment by oSumAtrIX** [comment]
What is the motivation for this PR?

**Comment by Ushie** [comment]
> What is the motivation for this PR?

#504

**Comment by kazimmt** [comment]
> What is the motivation for this PR?

Screenshot_2022-11-12-23-19-01-271_com chrome canary-edit

**Comment by trmdi** [comment]
I still have a question: should the Manager and Youtube Revanced have different icons?

**Comment by kazimmt** [comment]
> I still have a question: should the Manager and Youtube Revanced have different icons?

Maybe in future (when ReVanced team officialy release a new icon)

**Comment by trmdi** [comment]
> > I still have a question: should the Manager and Youtube Revanced have different icons?
> 
> Maybe in future (when ReVanced team officialy release a new icon)

Got it. Thank you for your excellent work for now.

**Comment by trmdi** [comment]
I've jus read on the Discord channel that the final icon is going to be chosen soon this month. So maybe you should wait until then?

**Comment by kazimmt** [comment]
I'm closing this PR

**Pull request closed without merging**
