### PR TITLE
feat:add continue anyway button to feature not implemented dialog

### PR DESCRIPTION
**Pull request by andrisas**

### CODE REVIEW

**Comment by andrisas** [comment]
Can someone review this?

**Comment by Ushie** [comment]
Hey! sorry for the late review

The restriction is intentional, so there shouldn't be a "Continue anyways" button, by any chance are you able to change it into "Cancel" instead?

**Comment by Ushie** [comment]
Thank you for your contribution! I couldn't make changes on your repository so I merged this and committed the required changes

**Comment by SodaWithoutSparkles** [comment]
> Hey! sorry for the late review
> 
> The restriction is intentional, so there shouldn't be a "Continue anyways" button, by any chance are you able to change it into "Cancel" instead?

@Ushie why is this merged then?

**Comment by Ushie** [comment]
> > Hey! sorry for the late review
> > The restriction is intentional, so there shouldn't be a "Continue anyways" button, by any chance are you able to change it into "Cancel" instead?
> 
> @Ushie why is this merged then?

I left a comment above yours

**Comment by SodaWithoutSparkles** [comment]
Ah I see, you changed it into cancel in another commit. 

https://github.com/revanced/revanced-manager/commit/cfc866bef2497bc1675bf5dea834cea59d9cc969

**Pull request merged**
