### PR TITLE
added arabic translation

### PR DESCRIPTION
**Pull request by XandarNull**
added Arabic translation for the app, I didn't know how to edit settings_viewmodel.dart and other options to integrate the translation into the app though so I'll leave that to you.
much love.

### CODE REVIEW

**Comment by mioscape** [comment]
Hello

**Comment by Fertanima** [comment]
Close this issue. Translations will be with Crowdin.

**Comment by XandarNull** [comment]
> Close this issue. Translations will be with Crowdin.

lmao it's not your call, it's not an issue it's a pr, and the devs can decide if they want to merge it or set up a crowdin, which they can just download the ar.json file and put it into crowdin and it would also work

**Comment by Anan-Saadi** [comment]
I think we might have some issues with right-to-left

**Comment by XandarNull** [comment]
> I think we might have some issues with right-to-left

not really, flutter handles it really well, you can compile the app with my ar.json as en.json and check.

**Comment by Ushie** [comment]
Translations for ReVanced Manager can be done on [Crowdin](https://translate.revanced.app/)

**Comment by XandarNull** [comment]
> Translations for ReVanced Manager can be done on [Crowdin](https://translate.revanced.app/)

Reas when the pull request was posted

**Pull request closed without merging**
