### PR TITLE
chore: remove unused dependencies

### PR DESCRIPTION
**Pull request by BenjaminHalko**
Removes unused dependencies:
- `flex_color_scheme`
- `flutter_dotenv`
- `flutter_launcher_icons`
- `flutter_svg`
- `flutter_test`
- `get_it`
- `http`
- `pull_to_refresh`

(I also decided to sort the dependencies alphabetically)

### CODE REVIEW

**Review by oSumAtrIX — APPROVED** [review]

**Review by validcube — CHANGES_REQUESTED** [review]
Don't we use `pull_to_refresh` in Dashboard?

Please verify.

**Comment by KTibow** [comment]
Seemingly not?
image

**Review by validcube — CHANGES_REQUESTED** [review]
🥞 Tested using Dart static analysis, no import issue found.

**Review by validcube — APPROVED** [review]
I hit the wrong button....

**Pull request merged**
