### PR TITLE
fix: aborting message changed

### PR DESCRIPTION
**Pull request by YarostheLaunchpadder**
Fixed issue #906

### CODE REVIEW

**Review by EvadeMaster — CHANGES_REQUESTED** [review]
:stop_sign: Your PR looks good to me, please rebase it to the `dev` branch.

**Comment by Ushie** [comment]
No need for rebase, GitHub PRs are acting weird the last few days

**Comment by EvadeMaster** [comment]
> No need for rebase, GitHub PRs are acting weird the last few days, feel free to merge

Whoops :trollface:

**Review by EvadeMaster — APPROVED** [review]
:tada: Looks good to me!

**Pull request merged**
