### PR TITLE
feat: Download Apps

### PR DESCRIPTION
**Pull request by BenjaminHalko**
A translation of the download apps feature from the compose version of ReVanced Manager.

The API was translated from [these files](https://github.com/ReVanced/revanced-manager-compose/tree/dev/app/src/main/java/app/revanced/manager/network/downloader).

TODO:
- [x] Recreate the API
- [ ] Add in the GUI
- [ ] Fix all the bugs

### CODE REVIEW

**Comment by BenjaminHalko** [comment]
Tested the API with this, but there might be more bugs to fix:
```dart
void main() {
  final downloader = APKMirror();
  downloader.getAvailableVersions('com.google.android.youtube', {'18.33.40'}).listen((apkMirrorApp) {
    apkMirrorApp.download('E:/temp', false);
  });
}
```

**Comment by Ushie** [comment]
Hey! thanks for the PR

I would pause development for this PR in the meantime until everything is discussed, as the ReVanced Manager Compose implementation is not complete in any way and is considered "wrong"

To clarify, we're aiming for a plug-in download system, where there would be a plugin for each "provider" such as APKMirror, APKPure or your own private CDN, anybody would be able to develop a plugin and simply plug it in

**Comment by Ushie** [comment]
That aside, would you like to help maintaining this repository? you've been helpful and have opened multiple feat PRs

**Comment by BenjaminHalko** [comment]
Yeah I agree, a plugin system would be a lot better.

Sure I can help maintain, thanks for the opportunity!

**Comment by Ushie** [comment]
Do you have a Discord account? if so, join [our server](https://revanced.app/discord) and ping @ush1e

**Comment by BenjaminHalko** [comment]
Has development on the plugin system been started yet?

**Comment by Ushie** [comment]
I don't believe so, no

**Comment by BenjaminHalko** [comment]
Shall I close this pr, or leave it open for future use...

**Comment by Ushie** [comment]
It can be closed, considering that ReVanced Manager Compose will likely be released not much after the implementation of plugins

**Pull request closed without merging**
