### PR TITLE
chore: merge `dev` branch to `main` branch

### PR DESCRIPTION
**Pull request by EvadeMaster**
## Merge `dev` branch to `main` branch

13 Commits (5+4+3+1)

* 🎉 5 New Features
* 🐛 4 Bug Fixes
* 📝 3 Documentation Improvements 
* 🧹 1 Miscellaneous Changes

### CODE REVIEW

**Comment by TheAabedKhan** [comment]
I didn't understand what problem you faced with https://github.com/revanced/revanced-manager/commit/5e7458ff1cc2e98d70a34fbcd21e350d9cc4bce6. Did you test it?

**Comment by Ushie** [comment]
Also this PR should wait for the remaining open PRs to be merged

**Comment by Ushie** [comment]
> > The problem with this commit is that it selects all compatible (and universal) patches
> 
> @EvadeMaster, can you attach a screen recording of the problem please?

@EvadeMaster asked me to respond to you with this recording

https://github.com/revanced/revanced-manager/assets/79272171/f9d238a7-86b7-4812-96ab-6da2390aaa17

**Comment by TheAabedKhan** [comment]
Even if you remove the commit, the same patches are selected. That's because the app automatically selects the Default patches if you have never made any patches selection. Once you select just the package you want, and hit Done, then it won't be overridden.

So, the PR does not have any issues. It doesn't break anything. It just stops the experimental patches from being selected (if Experimental patches support is turned off) while importing.

**Comment by EvadeMaster** [comment]
> Even if you remove the commit, the same patches are selected. That's because the app automatically selects the Default patches if you have never made any patches selection. Once you select just the patches you want, and hit Done, then it won't be overridden.
> 
> So, the PR does not have any issues. It doesn't break anything. It just stops the experimental patches from being selected (if Experimental patches support is turned off) while importing. 

Ah sorry about that, I have remove the warning status of this PR, and I'm sorry about the late reply too, I'm very busy right now.

**Review by Aunali321 — APPROVED** [review]
LGTM

**Pull request merged**
