### PR TITLE
feat: Use `/data/adb/revanced` again and ensure migration scenario

### LINKED ISSUE #283: feat: Custom patched APKs store path
### Type

Functionality

### Manager Branch

Flutter

### Issue

I don't feel like `/data/local/tmp` is a good directory to store patched APKs. Even though this directory is never cleaned by Android itself, many rooted apps and optimization scripts do. It's just a minor inconvenience to re-patch everything again if you forgot to back things up.

### Feature

Custom patched APKs store path should be a feature. This means you could even store it in external storage (storage cards, etc). Meaning you could do a full factory reset and the patched APK could still be recognized.

Though this may require some changes because of how ReVanced Manager store data of patched apps, it doesn't store it anywhere, but in its data. Causing you to lose some of the patched app's metadata when reinstalling ReVanced Manager. This is made into a separated issue, #285 .

### Motivation

Many builders store it elsewhere. Reis' builder for example, stores it in `/data/adb/revanced`. Which I find easier to access because it's closer to where the mount scripts are (`/data/adb/service.d`).

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

### PR DESCRIPTION
**Pull request by ponces**
Closes #283, #515 and #860.

### CODE REVIEW

**Review by Aunali321 — APPROVED** [review]

**Comment by ponces** [comment]
Any news on this?

**Review by Aunali321 — APPROVED** [review]
Approved, Thanks!

**Comment by ponces** [comment]
> Approved, Thanks!

? What? It was already approved by you...

**Comment by Ushie** [comment]
Thank you pomses!

**Comment by ILoveOpenSourceApplications** [comment]
@Ushie, the issues mentioned here which will be resolved/closed with this commit are still left open. Any reason for that?

**Comment by oSumAtrIX** [comment]
@ILoveOpenSourceApplications this is because

- The closing syntax is not followed in the description of the PR 
- The native feature by GitHub is not used:
Screenshot_2023-07-13-13-35-55-74_984e1414ae90666a90f12ff17ec14a7f

**Pull request merged**
