### PR TITLE
refactor: update deprecated and minor code refactors

### PR DESCRIPTION
**Pull request by saileshbro**

### CODE REVIEW

**Review by EvadeMaster — CHANGES_REQUESTED** [review]
Please remove `const` because `CacheConfig` isn’t a const constructor

```
lib\services\crowdin_api.dart:14:59
lib\services\github_api.dart:16:60
lib\services\revanced_api.dart:19:60
```

The constructor being called isn’t a const constructor. - https://dart.dev/tools/diagnostic-messages#const_with_non_const

**Comment by saileshbro** [comment]
@EvadeMaster please have a look now.

**Comment by EvadeMaster** [comment]
> @EvadeMaster please have a look now.

Upon installing the application via `flutter run`, the application crashed and threw an error.

## Log
```shell
I/flutter ( 8437): Error while creating ManagerAPI
I/flutter ( 8437): Stack trace:
I/flutter ( 8437):  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter ( 8437): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter ( 8437): #2      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:372:7)
I/flutter ( 8437): #3      _GetItImplementation.get (package:get_it/get_it_impl.dart:393:29)
I/flutter ( 8437): #4      _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
I/flutter ( 8437): #5      StackedLocator.call (package:stacked_core/src/code_generation/locator/stacked_locator.dart:85:17)
I/flutter ( 8437): #6      new ManagerAPI (package:revanced_manager/services/manager_api.dart:21:43)
I/flutter ( 8437): #7      setupLocator.<anonymous closure> (package:revanced_manager/app/app.locator.dart:35:39)
I/flutter ( 8437): #8      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160:41)
I/flutter ( 8437): #9      _GetItImplementation.get (package:get_it/get_it_impl.dart:409:34)
I/flutter ( 8437): #10     _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
I/flutter ( 8437): #11     StackedLocator.call (package:stacked_core/src/code_generation/locator/stacked_locator.dart:85:17)
E/flutter ( 8437): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type SharedPreferences is not registered inside GetIt.
E/flutter ( 8437): (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
E/flutter ( 8437): Did you forget to register it?)
E/flutter ( 8437): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 8437): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 8437): #2      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:372:7)
E/flutter ( 8437): #3      _GetItImplementation.get (package:get_it/get_it_impl.dart:393:29)
E/flutter ( 8437): #4      _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
E/flutter ( 8437): #5      StackedLocator.call (package:stacked_core/src/code_generation/locator/stacked_locator.dart:85:17)
E/flutter ( 8437): #6      new ManagerAPI (package:revanced_manager/services/manager_api.dart:21:43)
E/flutter ( 8437): #7      setupLocator.<anonymous closure> (package:revanced_manager/app/app.locator.dart:35:39)
E/flutter ( 8437): #8      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160:41)
E/flutter ( 8437): #9      _GetItImplementation.get (package:get_it/get_it_impl.dart:409:34)
E/flutter ( 8437): #10     _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
E/flutter ( 8437): #11     StackedLocator.call (package:stacked_core/src/code_generation/locator/stacked_locator.dart:85:17)
E/flutter ( 8437): #12     main (package:revanced_manager/main.dart:20:26)
E/flutter ( 8437): <asynchronous suspension>
E/flutter ( 8437):
```

##### Tested on `flutter` & `dev` branch.

**Review by EvadeMaster — DISMISSED** [review]
see https://github.com/revanced/revanced-manager/pull/710#issuecomment-1445020359

**Comment by saileshbro** [comment]
@EvadeMaster you need to run the generation to generate the dependency injection for the `SharedPreferences`

**Comment by EvadeMaster** [comment]
> @EvadeMaster you need to run the generation to generate the dependency injection for the `SharedPreferences`
> 
> ```shell
> flutter pub run build_runner build --delete-conflicting-outputs
> ```

I.. I- yeah,
###### kill me, aaaaaaaaaaaaaaaa
I'm very, very sorry about that, yeah, I just reviewed your PR, LGTM 👍

**Review by EvadeMaster — APPROVED** [review]

**Pull request merged**
