### PR TITLE
Targeted ads

### PR DESCRIPTION
**Pull request by validcube**
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/validcube/validcube/main/assets/ReVancedManager/default-dark.webp">
  
</picture>

## Pull Request
This will greatly help us to continue providing the service you know and love - YouTube ReVanced for much longer!!!!!

### CODE REVIEW

**Comment by PalmDevs** [comment]
This will earn us so much money!

**Comment by Ushie** [comment]
Testing and making an AdMob ID

**Review by Aunali321 — APPROVED** [review]

**Comment by validcube** [comment]
🙂‍↔️ After back and forth with the administrator, we have decided to postpone the project for ReVanced:NEXT, thank you for following the development of ReVanced.

**Comment by PalmDevs** [comment]
Can we bring this back? This would be seriously helpful.

**Comment by Ushie** [comment]
It's on the internal milestone

**Pull request closed without merging**
