### PR TITLE
fix: the issue that makes `manager` apply the wrong patch when there are duplicate patch names.

### PR DESCRIPTION
**Pull request by d4rkk3y**
This PR fix a issue that manager possibly apply wrong patch when there are 2 or more patch intended for different package name but have same patch name.
Issue: https://github.com/revanced/revanced-patches/pull/1082
If this issue was fixed then this https://github.com/revanced/revanced-patches/pull/1085 can be merged.

### CODE REVIEW

**Comment by Canny1913** [comment]
Was this PR tested?

**Comment by d4rkk3y** [comment]
> Was this PR tested?

I tested with current official patch file and it worked fine. I did not test with patch from https://github.com/revanced/revanced-patches/pull/1085 because I did not know how to import custom patch file to revanced manager. How can I do that?

**Comment by Canny1913** [comment]
> > Was this PR tested?
> 
> I tested with current official patch file and it worked fine. I did not test with patch from [revanced/revanced-patches#1085](https://github.com/revanced/revanced-patches/pull/1085) because I did not know how to import custom patch file to revanced manager. How can I do that?

Use the custom sources option in settings and change the repo there

**Comment by d4rkk3y** [comment]
> Use the custom sources option in settings and change the repo there

After a hour struggling with semantic release, I tested it and it works as expected with https://github.com/revanced/revanced-patches/pull/1085 which have youtube and tiktok settings patch name 'settings'.

**Comment by Canny1913** [comment]
> > Use the custom sources option in settings and change the repo there
> 
> After a hour struggling with semantic release, I tested it and it works as expected with [revanced/revanced-patches#1085](https://github.com/revanced/revanced-patches/pull/1085) which have youtube and tiktok settings patch name 'settings'.

Yeah semantic is absolute pain.

**Pull request merged**
