### PR TITLE
feat: CustomScrollView in app and patches selector views

### PR DESCRIPTION
**Pull request by 55nknown**
## Back button and title:
image

## When scrolled:
image

### CODE REVIEW

**Comment by ponces** [comment]
Not sure we want this...
What do you think @Aunali321?

**Comment by Aunali321** [comment]
I dont like it either but every material 3 app has it.

**Comment by 55nknown** [comment]
The primary reason for this is to have a way to navigate back without using the system navigation bar. Also more padding at the top looks better in my opinion.

**Comment by ponces** [comment]
Thanks!

**Pull request merged**
