### PR TITLE
feat: added japanese translation

### PR DESCRIPTION
**Pull request by creeper-0910**

### CODE REVIEW

**Comment by escape0707** [comment]
Aren't translations supposed to happen on crowdin?

**Comment by creeper-0910** [comment]
> Aren't translations supposed to happen on crowdin?

Oh, I did not know about that.
Where is the url?

**Comment by escape0707** [comment]
> Where is the url?

https://crowdin.com/project/revanced

I only read that they tried to do the translation in some GitHub issue. It's not promoted yet, and I find the page by googling it.

**Comment by creeper-0910** [comment]
> > Where is the url?
> 
> https://crowdin.com/project/revanced
> 
> I only read that they tried to do the translation in some GitHub issue. It's not promoted yet, and I find the page by googling it. The project is created by one of the mod so it's legit, ig.

Thank you!
I will send a correction there as well.

**Comment by Ushie** [comment]
Translations for ReVanced Manager can be done on [Crowdin](https://translate.revanced.app/)

**Pull request closed without merging**
