### PR TITLE
feat: Adding support for Exporting APK

### PR DESCRIPTION
**Pull request by nkitsaini**
Allows users to export APK once it's patched. 
I'm using [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) intent for export. This has it's benefits.

* We get to populate initial name for exported file, but user can edit before exporting
* We don't need to care about permissions and folder locations. We get a ContentUri and we just have to write apk there.
* Export is not limited to local filesystem. APK can be exported to other implementations like Google Drive out of the box.

Fixes: #140

### CODE REVIEW

**Comment by proxykingdev** [comment]
fantastic. i was waiting for this. very useful

**Comment by Ushie** [comment]
is this still being worked on?

**Comment by nkitsaini** [comment]
@Ushie Yes. I've cleaned up the PR. It is ready for review.

**Comment by Aunali321** [comment]
@nkitsaini any reason for using platform channels (kotlin) instead of dart? i am pretty sure the feature you're trying to implement is possible in dart. The reason we avoid platform channels is because they are very slow compared to dart.

**Comment by nkitsaini** [comment]
@Aunali321 I'm relatively new to android/flutter development so please correct me if I'm wrong. But as I understand it, if you need to get the Activity Result then you have to do it using native code.

Ideally there should a flutter library that wraps this whole logic and exposes via a dart api but I couldn't find it.

There's [android_intent_plus](https://pub.dev/packages/android_intent_plus), but it only seems to launch the `Intent` but not return the result.
I was able to find one library [cr_file_saver](https://pub.dev/packages/android_intent_plus) that let's you export files from dart but it's very new (less then a month old), so not sure about its stability.

I'll search more about Android Activity and how they work with flutter.

**Comment by Aunali321** [comment]
can you test if `cr_file_saver` works? if so we can avoid platform channels. and using new packages isnt a problem in alpha. we can always revert hence "alpha". Thank you!

**Comment by nkitsaini** [comment]
@Aunali321

It mostly works. There's just a minor bug around initial file name for export but I've added a [work around](https://github.com/revanced/revanced-manager/pull/439/files#diff-e0ef5e8d22a0beaf4e08655dcc8fe9a39b15a73d908b33e1f911c7225513e1d8R238) for now.


Overall the implementation is much simpler and I'll also try to get this bug fixed on `cr_file_saver`.

**Review by Aunali321 — APPROVED** [review]

**Pull request merged**
