### PR TITLE
fix: delete tests

### PR DESCRIPTION
**Pull request by 55nknown**
Flutter tests aren't used currently.

### CODE REVIEW

**Comment by ponces** [comment]
Meh... Why is this needed?

**Comment by 55nknown** [comment]
Why have tests if you're not using them?

**Comment by ponces** [comment]
Meh... Default Flutter template creates them and we should have in the future...
Anyway, I can merge this. Please amend commit message to use `fix` scope instead of `misc`

**Comment by 55nknown** [comment]
Done.

**Comment by ponces** [comment]
Thanks!

**Pull request merged**
