### PR TITLE
docs(fixed): replaced some emoji icons, not rendering on chromium based browsers on windows

### PR DESCRIPTION
**Pull request by neosubhamoy**
improved overall docs appearance

### CODE REVIEW

**Comment by PalmDevs** [comment]
What's the difference between this change and the current documentation? Can you post screenshots?

**Comment by validcube** [comment]
I cannot confirm this on **Windows 11 (23H3), Edge 115 & Chrome 118**,  The emoji looks fine to me,

image

**Comment by neosubhamoy** [comment]
Apologise! for the confusion...!! Actually, the problem is not with **Windows11(Any Version)**. it's only happening on the latest **Windows10 (22H2)** and older versions. Tested on latest versions of: **Chrome**, **Edge** & **Brave** (Firefox doesn't have any issues as it uses its own emoji rendering system)
The problem is Windows10 has horrible emoji Unicode support (Does not have support for the new **Screwdriver**, **Ladder**, etc. emojis)

Take a look at these screenshots below:

revanced-managerdocs1_installation md at main · ReVancedrevanced-manager
revanced-managerdocs2_1_patching md at main · ReVancedrevanced-manager
revanced-managerdocsREADME md at main · ReVancedrevanced-manager (1)

Hope you got the point...!!

**Comment by validcube** [comment]
Thoughts? @Ushie @oSumAtrIX

**Review by validcube — APPROVED** [review]
💫 Changes approved!

I can also confirm this on Windows 10

**Comment by taku-nm** [comment]
Can confirm. I have noticed this issue before but didn't think much of it. Win10 22H2

**Pull request merged**
