### PR TITLE
perf: Do not load patches twice

### PR DESCRIPTION
**Pull request by oSumAtrIX**
# TODO

Fix the issue with reloading patches after patching.

### CODE REVIEW

**Comment by BenjaminHalko** [comment]
@oSumAtrIX What exactly is not working?

**Comment by Ushie** [comment]
Copied from Discord:
"Basically after patching once, trying to patch again is not possible because the patches have to be reloaded"

**Comment by BenjaminHalko** [comment]
Are there specific patches that don't work after patching?

**Comment by oSumAtrIX** [comment]
@BenjaminHalko after patching once, when you revisit the page to chose an app to patch, it shows 0 patches for every app

**Comment by BenjaminHalko** [comment]
Oh I see, I was using universal patches. After switch to patching the YouTube app I can see it now.

**Comment by BenjaminHalko** [comment]
@oSumAtrIX Done.

**Comment by Ushie** [comment]
Please merge with squash next time

**Comment by oSumAtrIX** [comment]
The PR was not squashed with intention as it contains multiple commits that should not be squashed like rewording, or bumping

**Pull request merged**
