### PR TITLE
feat: ability to store and load selected patches

### PR DESCRIPTION
**Pull request by Mipirakas**
It works reliably but this is probably not the correct way of doing things.
Also, the UI is crap but i don't know how else to do it.
Please provide feedback.

### CODE REVIEW

**Comment by Aunali321** [comment]
I will take a look at this later, Thanks!

**Comment by Mipirakas** [comment]
Should a json file format be used? The only benefit I can see would be that it would be easier to store all the patches from multiple apps in a single file. Currently it is 1 file per patched app.

**Comment by Mipirakas** [comment]
Ok so i'm now using a single json file to store the selected patches and the ui is much better now too, albeit not that intuitive.
The only things i'm not certain of are the file location, the I18n strings and maybe some programming conventions that i overlooked.
But otherwise working great.

**Comment by trmdi** [comment]
> the UI is crap

Could you post the screenshot?

**Comment by Mipirakas** [comment]
> Could you post the screenshot?

I don't have the old ui that was "crap" anymore but trust me, it was bad.
Here is a screeshot of the current ui. Tapping the save icon will load your saved patches, and long pressing it will save your currently selected patches.
Thoughts?
image

**Comment by trmdi** [comment]
Couldn't it just remember the last state from the user?

**Comment by Ushie** [comment]
> > Could you post the screenshot?
> 
> I don't have the old UI that was "crap" anymore but trust me, it was bad. Here is a screenshot of the current UI. Tapping the save icon will load your saved patches, and long pressing it will save your currently selected patches. Thoughts? image

It would probably be best to use a dropdown here, "Save patches selection" and "Load patches selection" should be separated, not in a single icon button

**Comment by Ushie** [comment]
> Couldn't it just remember the last state from the user? That would keep it simple. If somehow the chosen checkboxes are reset, we should find and fix that other bug instead.

That's an already existing feature, it's just a bug that it doesn't work

**Comment by Mipirakas** [comment]
> It would probably be best to use a dropdown here, "Save patches selection" and "Load patches selection" should be separated, not in a single icon button

What exactly do you mean by dropdown? Like a dropdownbutton? I don't know if that will work since there is no room in the SliverAppBar for a menuItem with Text. I am very new to Flutter and UI design in general so if you have a specific widget in mind or if i should try to create one from scratch, please let me know.

> That's an already existing feature, it's just a bug that it doesn't work

Where is this functionality located? I can't seem to find it in either patches_selector_viewmodel.dart or patcher_viewmodel.dart

**Comment by Indranil012** [comment]
There should be a "three dot menu" for these options and maybe for future options.

**Comment by Mipirakas** [comment]
> There should be a "three dot menu" for these options and maybe for future options.

Yes thank you, I don't know why I didn't think of that. Especially after seeing such menus every day in the past 10 years.

**Comment by trmdi** [comment]
I still have doubt about this feature. Do you really need to share the checked list?

**Comment by Mipirakas** [comment]
> I still have doubt about this feature. Do you really need to share the checked list?

I didn't make this to be able to share your selected patches. I made this to quickly be able to load your preferred patches so the update process goes quicker. I did not know this functionality was already there because i don't see it in the source code.

But you are right, I'll have a look.

**Comment by Ushie** [comment]
> if you have a specific widget in mind
Refer to your Export APK PR, that was in a dropdown
> Where is this functionality located?
I personally don't know, you'd have to ask @Aunali321 (you can join the discord server and ask him there if preferred, p.s. drop me your Discord tag when you do join 😊)

**Comment by Mipirakas** [comment]
> Refer to your Export APK PR, that was in a dropdown

I wasn't the author of that PR but I'll take a look.

> I personally don't know, you'd have to ask @Aunali321 (you can join the discord server and ask him there if preferred, p.s. drop me your Discord tag when you do join 😊)

Alright, I've joined. Mipirakas#4661

**Comment by Ushie** [comment]
> I wasn't the author of that PR but I'll take a look.

Oh 🤐 that's my mistake, my bad! I was under the assumption it was you that authored it this whole time 😅

**Comment by Mipirakas** [comment]
I have created another PR (https://github.com/revanced/revanced-manager/pull/477) which does not create a json file anymore but simply remembers your last selection.
Should I rework this PR to import/export patches selection in a json file or is it fine to discard this PR?
As others have stated, why would you want to import/export patches selection. I don't really see the use cases?

**Comment by Mipirakas** [comment]
Everything working.
Please test and report back if you want some behavioral changes or code quality improvements.

**Comment by trmdi** [comment]
> As others have stated, why would you want to import/export patches selection. I don't really see the use cases?

Is this PR still needed?

**Comment by Mipirakas** [comment]
> Is this PR still needed?

Yes. This now does everything at once. It was discussed on discord. The other PR is closed.

**Comment by trmdi** [comment]
Btw, this issue probably somehow relates to what you're working on. Could you have a look on that?
https://github.com/revanced/revanced-manager/issues/418

**Comment by Mipirakas** [comment]
Ok, I don't know why, but the import or export feature is borked right now. I can't select json files to import in the default filepicker, if i have exported them with the export feature. However if i pick the same json file with a different filemanager it works just fine.
Also, manually created json files can be picked with the import feature default filepicker. I have no idea what's going on...

**Comment by trmdi** [comment]
> Ok, I don't know why, but the import or export feature is borked right now. I can't select json files to import in the default filepicker, if i have exported them with the export feature. However if i pick the same json file with a different filemanager it works just fine. Also, manually created json files can be picked with the import feature default filepicker. I have no idea what's going on...

I feel this import/export json feature is not really needed. For normal usecases, I guess users probably never need to use the feature.

**Comment by Mipirakas** [comment]
Ok, import/export feature fixed now. The issue was that FilePicker cached the json file and did not update the cache when selecting a new file with the same path and filename.
Good to go now.

**Comment by Aunali321** [comment]
Thank you!

**Pull request merged**
