### PR TITLE
Support Gitea repositories for patches

### PR DESCRIPTION
**Pull request by logykk**
Adds the ability to pull patches & integrations from any Gitea repository.
This should help to reduce ReVanced's reliance on GitHub for supplying patches, at least until a more detailed/permanent solution is ready.

### CODE REVIEW

**Comment by Aunali321** [comment]
Is this properly tested and ready to merge?

**Comment by rihaq** [comment]
Correct! https://giveupgithub.org

**Comment by Aunali321** [comment]
Thanks!

**Comment by rihaq** [comment]
@Aunali321 wow you don't take me seriously now see what github doing

**Comment by Aunali321** [comment]
> @Aunali321 wow you don't take me seriously now see what github doing

I do not have time to look at individual issues and feature requests. I can not contribute to this project full time. If you want a feature, make a pull request but make sure to open an issue beforehand to discuss it.

**Pull request merged**
