### PR TITLE
feat: Added Chinese (Traditional) translations

### PR DESCRIPTION
**Pull request by RobotHanzo**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Can someone check this

**Comment by z-huang** [comment]
I can read this. The translation has no problem.

**Comment by e5u** [comment]
I can also read it, there is no problem with this translation.

**Comment by Sculas** [comment]
The manager is going to be rewritten, meaning all translations will be invalidated. So I'm going to close this PR. Thank you for your contribution!

**Pull request closed without merging**
