### PR TITLE
refactor: rearranged readme sections and linked to Vanced MicroG

### PR DESCRIPTION
**Pull request by afnzmn**

### CODE REVIEW

**Comment by BubuXP** [comment]
Two things are bad in this commit: the removing of the disclaimer about being an alpha version, and pointing to the old Vanced MicroG.

User inotia00 made two more recent versions of MicroG:
https://github.com/inotia00/VancedMicroG/releases
This one follows Vanced version closely, as a continuation of their work;

https://github.com/inotia00/VancedMicroG_v2/releases
This version is called v2 because of some changes compared to the other version, it removed unused parts of MicroG and leaves the original Google logo icon.

I'm using the v2 version right now and everything is working fine, the APK is also half the size compared to Vanced version.

**Comment by Ushie** [comment]
> the removing of the disclaimer about being an alpha version

It isn't removed, it's rearranged ([here] (https://github.com/revanced/revanced-manager/pull/371/commits/6705bba9a15a336594ad6bf0c425c7a587a1d2a5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R13))

**Comment by Ushie** [comment]
Misclick 😅

**Comment by Ushie** [comment]
> the removing of the disclaimer about being an alpha version

It isn't removed, it's rearranged [here](https://github.com/revanced/revanced-manager/pull/371/commits/6705bba9a15a336594ad6bf0c425c7a587a1d2a5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R13)

**Review by Aunali321 — APPROVED** [review]

**Pull request merged**
