### PR TITLE
fix(ui): Support free-scroll and auto-scroll for the installer logs (#1736)

### LINKED ISSUE #1736: feat: Allow free scrolling in patching screen
### Feature description

Allow the user to scroll freely in the patching screen and read the patch logs if they want to. The view should (still) lock to the bottom of the patch log if the user scrolls back to the bottom of the page (and/or put an arrow to scroll to the bottom, like in Discord).

### Motivation

Currently, the user is allowed to scroll up but the manager will force the view back to the bottom of the patch log every time a new line is added, making it impossible to read the patch log until it is finished. Why even allow the user to scroll up while patching is still ongoing?

Freely scrolling in the patch screen will allow users to properly read the patch logs and immediately start investigating if an error or failure occurs.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

### PR DESCRIPTION
**Pull request by Domenic-MZS**
# 🔧🎨 UI Fix: Enhance Installer Logs Autoscroll Feature (#1736)
This PR fixes #1736, reported by @KobeW50 

### Overview
The installer logs' functionality has been enhanced by introducing a dynamic auto-scroll feature, **Allowing free scrolling when the user pans** the scroll. However, if the user **scrolls down to the bottom or hits the auto-scroll-button** it will **lock in-place** again  improving the user experience/curiosity during the installation processes. 

- **Issue:** The Installer Logs always scrolls down on any log update disturbing the user reading experience (being a sh* annoying imo xD).
- **Context:** The current functionality lacks dynamic autoscroll behavior, forcing a repaint, auto-scrolling to then afterwards (after 1 sec of the listeners notification - yup, a magic number).
- **Related Solutions:** Similar to Discord's autoscroll behavior, the enhancement should allow the user to freely scroll.
- **Impact:** Significantly improves user experience during installation processes.

### 📓 Description
This PR introduces dynamic autoscroll behavior to the installer logs. The autoscroll feature listens for user pan interactions, allowing for intelligent autoscroll control/toggle. Users can detach autoscroll by start dragging out or holding, and it can reattach the tail (follow) by clicking the "go to bottom" FAB button or manually scrolling to the bottom (anchor point sweet point at `95%`).

### ✍🏼 Changes Made
- Added dynamic auto-scroll feature to installer logs on user interactions.
- Enhance the scroll to bottom function to synchronize with the engine repaints by using the WidgetsBinding callback
- Add FAB button to automatically reattach the auto-scroll.

<details>
<summary>Technical overview</summary>

 - Wrapped the CustomScroll of the logs with a NotificationListener to handle scroll events for detach and conditional attach the auto scroll
 - Wrapped the CustomScroll with a Stack to display on top the Scroll2Bottom button
 - Added 3 flags for handling needed states (to avoid bugs) 
   - `_isAutoScrollEnabled`: flag to automatically call scroll to bottom on incoming data
   - `_isAutoScrolling`: flag to lock the current scroll configuration like a loading or busy state until scrolled
   - `showAutoScrollButton`: flag to render the Scroll to bottom [FAB](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html) button on the stacked screen
   - Wrap the animate to bottom scroll to be executed only after a frame is render - to avoid visual inconsistencies and enhance the framerate
</details>

### 🦯 Testing
- [x] ~Update Tests (ToDo - Not Found nor needed for now...)~
- [x] Compile/Build code 
  - 🐞 Tested with `Stable Flutter v3.19.3` and `dart 3.3.1`.
  - **System:** Linux archlinux 6.7.9-arch1-1 GNU/Linux

### 📋  Notes & References
- [Discord's autoscroll behavior](https://discord.com)
- [ScrollNotifications](https://api.flutter.dev/flutter/widgets/ScrollNotification-class.html)
- [Post Frame Callbacks](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)

### 🔬 Reviewers
N/A (any mod is ok)

---

👾 Feedback, changes, or suggestions are welcome! ✌🏼 🏖️ now a 🍕 emoji too... 
> ##### Note: @validcube i'm on the "pretty" PR's party too 🎉 !!

### CODE REVIEW

**Comment by validcube** [comment]
🙏 I can safely retire now

**Review by BenjaminHalko — APPROVED** [review]
LGTM!

**Comment by validcube** [comment]
🥞 LGTM!

- Reviewer note: *Limited to no testing done, due to availability issue.*

**Review by validcube — APPROVED** [review]

**Comment by Domenic-MZS** [comment]
Wow, that was blazingly fast 🔥 thanks @oSumAtrIX, @validcube, and @BenjaminHalko !!

**Pull request merged**
