### PR TITLE
fix: exported logs patch selection

### PR DESCRIPTION
**Pull request by BenjaminHalko**
fixes: #1531

### CODE REVIEW

**Review by Ushie — CHANGES_REQUESTED** [review]
```
App: com.laurencedawson.reddit_sync vv23.06.30-13:39
Patches version: v2.201.1
Patches added: Spoof client [OAuth client ID: j]
Patches removed: Disable ads, Disable Sync for Lemmy bottom sheet, Spoof client [OAuth client ID: j]
Options changed: None
```
Applying options makes it think that its both added and removed, and the options changed field stays None

**Comment by BenjaminHalko** [comment]
Did you disable the other 2 patches, or is that another bug as well?

**Comment by Ushie** [comment]
I did disable them

**Comment by Ushie** [comment]
The testing seems to have been effected by #1540, will retest when possible

**Comment by Ushie** [comment]
Hey, @validcube or @TheAabedKhan do you think it's possible to test this?

I don't have the time to build and test this

**Review by validcube — APPROVED** [review]
🥞 Tested & Approved

**Pull request merged**
