### PR TITLE
fix: Follow language update immediately

### PR DESCRIPTION
**Pull request by snehithssv**
fixes : #1731

### CODE REVIEW

**Comment by TheAabedKhan** [comment]
Can you provide a screen recording of updating the language before and after the commit? Your commit is not fixing the issue on my end.

**Comment by snehithssv** [comment]
Yeah Sure... 
Before: -
https://github.com/ReVanced/revanced-manager/assets/112557710/aa1bffe8-ebfa-4211-8bd0-0ab479d295d0
After: -
https://github.com/ReVanced/revanced-manager/assets/112557710/9fb2bfe0-9f9b-46c7-8141-0c3309cc7909

**Comment by TheAabedKhan** [comment]
After the commit [`a56bdac`](https://github.com/ReVanced/revanced-manager/pull/1944/commits/a56bdac8b680555966976419fa5d507a84a75f32), the issue is fixed.
Thank you.

**Review by validcube — APPROVED** [review]
🥞 Approved, thanks! 

Compiled using Flutter 3.23.0-0.1.pre (Beta) and tested on physical devices running Android 14 (Samsung One UI 6.1 - 1st May)

**Pull request merged**
