### PR TITLE
feat: add Polish language

### PR DESCRIPTION
**Pull request by infevlol**

### CODE REVIEW

**Comment by pietryszak** [comment]
@infevlol https://github.com/revanced/revanced-manager/pull/76

**Review by pietryszak — COMMENTED** [review]
Not all text is translated. Mostly 120+ lines

**Comment by Daviteusz** [comment]
@infevlol I closed #76. I'm waiting for weblate/crowdin integration.

**Comment by Ushie** [comment]
Translations for ReVanced Manager can be done on [Crowdin](https://translate.revanced.app/)

**Pull request closed without merging**
