### PR TITLE
feat(patches-selector): Improve disabled card UI

### PR DESCRIPTION
**Pull request by ponces**
This includes hiding the "Warning" label on the disabled card as interacting with it only makes sense on an enabled card.

Before vs After:
Screenshot_20230612-221638

### CODE REVIEW

**Comment by ponces** [comment]
They will try to interact with it and the popup will clearly say it why.
Having an interactable subcomponent inside a non-interactable component does not make sense at all...

**Comment by oSumAtrIX** [comment]
The UI will not motivate the user to interact with it. The user will simply take for granted that it is not available, but not know why.

**Comment by ponces** [comment]
> The UI will not motivate the user to interact with it. The user will take for granted that it is unavailable but not know why. Before, the user was motivated by the interactive chip.

That's not true. The user is always tempted to click it anyway just to see what happens.
In fact, I only knew about the toast because I tried to interact with the greyed out card.
Yet again:
> Having an interactable subcomponent inside a non-interactable component does not make sense at all...

**Review by Aunali321 — APPROVED** [review]
Reasoning makes sense. Looks good to me.

**Review by EvadeMaster — APPROVED** [review]
:tada: Looks good to me!

**Comment by ponces** [comment]
Is anything missing?

**Pull request merged**
