### PR TITLE
chore: upgrade AGP to `8.2.0` + migrate deprecated functions

### PR DESCRIPTION
**Pull request by BenjaminHalko**

### CODE REVIEW

**Review by validcube — APPROVED** [review]
🥞 LGTM!

**Comment by validcube** [comment]
Not sure about migration to `TabRow` & `ScrollableTabRow` though, see

Compose Material 3 (1.2.0-alpha11): https://android-review.googlesource.com/c/platform/frameworks/support/+/2802595

**Comment by Axelen123** [comment]
Doesn't this PR do a lot more than just upgrading to AGP 8.2.0?

**Comment by validcube** [comment]
> Doesn't this PR do a lot more than just upgrading to AGP 8.2.0?

It does, the title of this PR should be change to bumping AGP and migrate deprecated functions.

**Comment by BenjaminHalko** [comment]
Should it be split in to 2 different prs or should I just change the title.

**Comment by Axelen123** [comment]
I think it is fine. Some parts seem to be related

**Pull request merged**
